### PR TITLE
Update schedule.md

### PR DESCRIPTION
**Pull request by sofer**
"if you prefer..."

### CODE REVIEW

**Comment by sofer** [comment]
@NataliaLKB could you check and merge.

**Comment by sofer** [comment]
Actually, I notice I have two overlapping merges on the same file. Ignore for now.

**Comment by iteles** [comment]
@sofer PR #12  now merged :+1:

**Comment by NataliaLKB** [comment]
@sofer and @iteles Though in the future I wouldn't mind helping review this. I was not a volunteer. Based on the last meeting @FilWisher , @rorysedgwick  and @benjaminlees were taking over this responsibility.

**Comment by NataliaLKB** [comment]
@rorysedgwick thanks!

**Comment by iteles** [comment]
@NataliaLKB :laughing: I thought that when I saw your name!

**Comment by NataliaLKB** [comment]
:wink:

**Comment by rorysedgwick** [comment]
No problem

**Pull request merged**
