### PR TITLE
Some initial notes on teaching

### PR DESCRIPTION
**Pull request by iteles**
I thought it would be important to capture our notes on 'teaching' somewhere within our 'open source' world as opposed to dotted throughout various boards on trello. 
These are only a few initial thoughts, I'm sure there's a lot I'm not thinking of off the top of my head and will only come to me next week 'in the thick of it'!

### CODE REVIEW

**Comment by iteles** [comment]
@NataliaLKB I know you're not a reviewer of PRs for the playbook, but as week 2 is so fresh in your mind, could you grab 5 minutes to scan this and add any glaring omissions (even as a comment here or an issue on the repo) please?

@rorysedgwick As you were also involved in week 2, please add/amend/delete anything you like. Thanks for reviewing!

@sofer You get automatic notices of all PRs on this repo right? I don't need to keep mentioning you in comments? :wink:

**Comment by NataliaLKB** [comment]
@iteles, this looks like a great start for me! If anyone feels that there should be more information in week two on outline syllabus, we have this list of [expected learning](https://hackpad.com/Week-Two-Expected-Learning-XFTPVTmz91p). Otherwise :+1: .

**Comment by iteles** [comment]
@NataliaLKB Ace, thanks, added in latest commit. We should have one of these for **every** week!

**Comment by NataliaLKB** [comment]
Agree!

**Comment by rorysedgwick** [comment]
Looks good to me, happy to merge.

Keeping track of technology and implementation choices for each week in detail will make things a lot easier when we come to this point next time around and are trying to remember which parts of each week worked well and the bits that could be changed.

Is there somewhere we can also include some pointers/comments from current students about each week? For example there were some calls for certain roles to be done in week one instead of delayed until week two and these will probably be worth taking into consideration for the next cohort.

**Comment by iteles** [comment]
@rorysedgwick Totally agree. I suggest we note these in the foundation.md document (which currently houses the curriculum) until we find a better place for them.
In the meantime there is also the [Stop, Go, Continue trello board](https://trello.com/b/8QZecGTM/stop-go-continue) where we take notes every week.

**Comment by sofer** [comment]
@iteles I am very happy with this. Merging now.

**Pull request merged**
